SELECT 	YMTRTBSTRD.STRATEGY AS "Strategy"
		, YMTRTBSTRD.DESCRIPTION AS "Description"
		, YMTRTBSTRPGM.PROGRAM_DESC AS "Program"
		, YMTRTBSTROFC.OFFICE_DESC AS "Office"
		, YMTRTBSTRTR2.TIER_II_DESC AS "Book"
		
FROM 	HS_NASTRIPES_SLT.YMTRTBSTRD AS YMTRTBSTRD
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRA AS YMTRTBSTRA ON YMTRTBSTRD.STRATEGY = YMTRTBSTRA.STRATEGY
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRPGM AS YMTRTBSTRPGM ON YMTRTBSTRA.YPROGRAM = YMTRTBSTRPGM.YPROGRAM
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRTR2 AS YMTRTBSTRTR2 ON YMTRTBSTRTR2.TIER_II = YMTRTBSTRA.TIER_II
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTROFC AS YMTRTBSTROFC ON YMTRTBSTRA.OFFICE = YMTRTBSTROFC.OFFICE
