/** Query for fetching a financial trades from TORA plus other attributes including strategies **/
-- NA STRIPES
SELECT 	YMTRDEFUT.TRADE_NUM AS "Trade ID"
		, YMTRDEFUT.TRADE_TYPE AS "Trade type"
		, YMTRDEFUT.TRADING_COMPANY AS "Trading company"
		, YMTRDEFUT.TRADING_NAME AS "Trading company name"
		, YMTRDEFUT.TRADE_DATE AS "Trade date"
		, YMTRDEFUT.MARKET AS "Market"
		, YMTRDEFUT.COMMODITY AS "Commodity"
		, YMTRTBFTHM.DESCRIPTION AS "Commodity description"
		, YMTRDEFUT.LOTS AS "Lots"
		, YMTRDEFUT.QTY AS "Quantity"
		, YMTRDEFUT.UOM AS "Quantity unit"
		, YMTRDEFUT.PRICE AS "Price"
		, YMTRDEFUT.CURRENCY AS "Currency"
		, YMTRDEFUT.PER AS "Per"
		, YMTRDEFUT.UNIT AS "Unit"
		, YMTRDEFUT.DELIVERY_MONTH AS "Delivery month"
		, YMTRDEFUT.TRADER AS "Trader"
		, YMTRTBUSER.NAME1 AS "Trader name"
		, YMTRDEFUT.STRATEGY AS "Strategy"
		, YMTRTBSTRD.DESCRIPTION AS "Strategy description"
		, YMTRTBSTRPGM.PROGRAM_DESC AS "Program"
		, YMTRTBSTROFC.OFFICE_DESC AS "Office"
		, YMTRTBSTRTR2.TIER_II_DESC AS "Book"
		, YMTRDEFUT.EXECUTING_BROKER AS "Executing broker"
		, LFA1_1.NAME1 AS "Executing broker description"
		, YMTRDEFUT.CLEARING_BROKER AS "Executing broker"
		, LFA1_2.NAME1 AS "Clearing broker description"
		, YMTRDEFUT.PS_BROKER AS "P&S indicator"
		, YMTRDEFUT.BROKER_MATCH AS "Broker match indicator"
		, YMTRDEFUT.FI_DOCUMENT AS "Financial document"
		, YMTRDEFUT.GJAHR AS "FI document year"
		, YMTRDEFUT.BUKRS AS "FI document company"
		, YMTRDEFUT.PARENT_TRADE_NUM AS "Parent trade"
		, YMTRDEFUT.TRADE_SPLIT AS "Split trade flag"
		, 'NA' AS "System"
	
FROM	HS_NASTRIPES_SLT.YMTRDEFUT AS YMTRDEFUT
		INNER JOIN HS_NASTRIPES_SLT.YMTRTBFTHM AS YMTRTBFTHM ON YMTRDEFUT.COMMODITY = YMTRTBFTHM.HYDROCARB AND YMTRDEFUT.MARKET = YMTRTBFTHM.MARKET
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRD AS YMTRTBSTRD ON YMTRDEFUT.STRATEGY = YMTRTBSTRD.STRATEGY
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRA AS YMTRTBSTRA ON YMTRTBSTRD.STRATEGY = YMTRTBSTRA.STRATEGY
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRPGM AS YMTRTBSTRPGM ON YMTRTBSTRA.YPROGRAM = YMTRTBSTRPGM.YPROGRAM
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRTR2 AS YMTRTBSTRTR2 ON YMTRTBSTRTR2.TIER_II = YMTRTBSTRA.TIER_II
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTROFC AS YMTRTBSTROFC ON YMTRTBSTRA.OFFICE = YMTRTBSTROFC.OFFICE
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBUSER AS YMTRTBUSER ON YMTRDEFUT.TRADER = YMTRTBUSER.BNAME
		LEFT JOIN HS_NASTRIPES_SLT.LFA1 AS LFA1_1 ON YMTRDEFUT.EXECUTING_BROKER = LFA1_1.LIFNR
		LEFT JOIN HS_NASTRIPES_SLT.LFA1 AS LFA1_2 ON YMTRDEFUT.CLEARING_BROKER = LFA1_2.LIFNR
		
WHERE	YMTRDEFUT.DEAL_STATUS <> 'DELE'
		AND YMTRDEFUT.TRADE_DATE BETWEEN '20220101' AND '20220630'
--		AND YMTRDEFUT.TRADE_DATE BETWEEN '20220701' AND '20221231'
--		AND YMTRDEFUT.TRADE_DATE BETWEEN '20230101' AND '20230630'
--		AND YMTRDEFUT.TRADE_DATE BETWEEN '20230701' AND '20231231'

UNION ALL

-- EU STRIPES
SELECT 	YMTRDEFUT.TRADE_NUM AS "Trade ID"
		, YMTRDEFUT.TRADE_TYPE AS "Trade type"
		, YMTRDEFUT.TRADING_COMPANY AS "Trading company"
		, YMTRDEFUT.TRADING_NAME AS "Trading company name"
		, YMTRDEFUT.TRADE_DATE AS "Trade date"
		, YMTRDEFUT.MARKET AS "Market"
		, YMTRDEFUT.COMMODITY AS "Commodity"
		, YMTRTBFTHM.DESCRIPTION AS "Commodity description"
		, YMTRDEFUT.LOTS AS "Lots"
		, YMTRDEFUT.QTY AS "Quantity"
		, YMTRDEFUT.UOM AS "Quantity unit"
		, YMTRDEFUT.PRICE AS "Price"
		, YMTRDEFUT.CURRENCY AS "Currency"
		, YMTRDEFUT.PER AS "Per"
		, YMTRDEFUT.UNIT AS "Unit"
		, YMTRDEFUT.DELIVERY_MONTH AS "Delivery month"
		, YMTRDEFUT.TRADER AS "Trader"
		, YMTRTBUSER.NAME1 AS "Trader name"
		, YMTRDEFUT.STRATEGY AS "Strategy"
		, YMTRTBSTRD.DESCRIPTION AS "Strategy description"
		, YMTRTBSTRPGM.PROGRAM_DESC AS "Program"
		, YMTRTBSTROFC.OFFICE_DESC AS "Office"
		, YMTRTBSTRTR2.TIER_II_DESC AS "Book"
		, YMTRDEFUT.EXECUTING_BROKER AS "Executing broker"
		, LFA1_1.NAME1 AS "Executing broker description"
		, YMTRDEFUT.CLEARING_BROKER AS "Executing broker"
		, LFA1_2.NAME1 AS "Clearing broker description"
		, YMTRDEFUT.PS_BROKER AS "P&S indicator"
		, YMTRDEFUT.BROKER_MATCH AS "Broker match indicator"
		, YMTRDEFUT.FI_DOCUMENT AS "Financial document"
		, YMTRDEFUT.GJAHR AS "FI document year"
		, YMTRDEFUT.BUKRS AS "FI document company"
		, YMTRDEFUT.PARENT_TRADE_NUM AS "Parent trade"
		, YMTRDEFUT.TRADE_SPLIT AS "Split trade flag"
		, 'EU' AS "System"
	
FROM	HS_EUSTRIPES_SLT.YMTRDEFUT AS YMTRDEFUT
		INNER JOIN HS_EUSTRIPES_SLT.YMTRTBFTHM AS YMTRTBFTHM ON YMTRDEFUT.COMMODITY = YMTRTBFTHM.HYDROCARB AND YMTRDEFUT.MARKET = YMTRTBFTHM.MARKET
		LEFT JOIN HS_EUSTRIPES_SLT.YMTRTBSTRD AS YMTRTBSTRD ON YMTRDEFUT.STRATEGY = YMTRTBSTRD.STRATEGY
		LEFT JOIN HS_EUSTRIPES_SLT.YMTRTBSTRA AS YMTRTBSTRA ON YMTRTBSTRD.STRATEGY = YMTRTBSTRA.STRATEGY
		LEFT JOIN HS_EUSTRIPES_SLT.YMTRTBSTRPGM AS YMTRTBSTRPGM ON YMTRTBSTRA.YPROGRAM = YMTRTBSTRPGM.YPROGRAM
		LEFT JOIN HS_EUSTRIPES_SLT.YMTRTBSTRTR2 AS YMTRTBSTRTR2 ON YMTRTBSTRTR2.TIER_II = YMTRTBSTRA.TIER_II
		LEFT JOIN HS_EUSTRIPES_SLT.YMTRTBSTROFC AS YMTRTBSTROFC ON YMTRTBSTRA.OFFICE = YMTRTBSTROFC.OFFICE
		LEFT JOIN HS_EUSTRIPES_SLT.YMTRTBUSER AS YMTRTBUSER ON YMTRDEFUT.TRADER = YMTRTBUSER.BNAME
		LEFT JOIN HS_EUSTRIPES_SLT.LFA1 AS LFA1_1 ON YMTRDEFUT.EXECUTING_BROKER = LFA1_1.LIFNR
		LEFT JOIN HS_EUSTRIPES_SLT.LFA1 AS LFA1_2 ON YMTRDEFUT.CLEARING_BROKER = LFA1_2.LIFNR
		
WHERE	YMTRDEFUT.DEAL_STATUS <> 'DELE'
		AND YMTRDEFUT.TRADE_DATE BETWEEN '20220101' AND '20220630'
--		AND YMTRDEFUT.TRADE_DATE BETWEEN '20220701' AND '20221231'
--		AND YMTRDEFUT.TRADE_DATE BETWEEN '20230101' AND '20230630'
--		AND YMTRDEFUT.TRADE_DATE BETWEEN '20230701' AND '20231231'
