SELECT	
		YMTRADEHDR.TRADE_NUM
		, YMTRADEHDR.TRADE_TYPE
		, YMTRADEHDR.TRADING_NAME
	 	, YMTRADEHDR.COUNTERPARTY
	 	, LFA1.NAME1
	 	, YMTRADEHDR.DEAL_STATUS
	 	, YMTRADEHDR.AGREE_DATE
	 	, YMTRADEHDR.START_DATE
	 	, YMTRADEHDR.END_DATE
	 	, YMTRADEHDR.CLOSE_OUT_DATE
	 	, YMTRADEHDR.CREATED_DATE
	 	, YMTRADEHDR.TRADER
	 	, YMTRTBUSER.NAME1
	 	, YMTRADEHDR.CONTRACT_ADMIN
	 	, YMTRADEHDR.APPROVER
	 	, YMTRADEHDR.TERM
	 	, YMTRADEHDR.ECONFIRM
	 	, YMTRADEHDR.NETTNG
	 	, YMTRADEITM.TRADE_NUM_ITEM
	 	, YMTRADEITM.TRAN_TYPE
	 	, YMTRADEITM.MATNR
	 	, YMTRADEITM.PROD_SHORT
	 	, YMTRADEITM.VOLUME
	 	, YMTRADEITM.MEINS
	 	, YMTRADEITM.TITLE_START
	 	, YMTRADEITM.TITLE_END
	 	, YMTRADEITM.TITLE_LOC
	 	, OIJLOC.LOCNAM
	 	, YMTRADEITM.STRATEGY
	 	, STRD.DESCRIPTION
	 	, STRA.YPROGRAM
	 	, LFA1.KTOKK
	 	, MARA.PRDHA
	 	, STRA.YGROUP
	 	, STRPGM.PROGRAM_DESC
	 	, STRA.TIER_II
	 	, STRTR2.TIER_II_DESC
	 
FROM 	HS_NASTRIPES_SLT.YMTRADEHDR as YMTRADEHDR
		INNER JOIN HS_NASTRIPES_SLT.YMTRADEITM AS YMTRADEITM ON YMTRADEHDR.TRADE_NUM = YMTRADEITM.TRADE_NUM 	
		INNER JOIN HS_NASTRIPES_SLT.LFA1 AS LFA1 ON YMTRADEHDR.COUNTERPARTY = LFA1.LIFNR
		LEFT JOIN HS_NASTRIPES_SLT.MARA AS MARA ON YMTRADEITM.MATNR = MARA.MATNR
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRD AS STRD ON YMTRADEITM.STRATEGY = STRD.STRATEGY
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRA AS STRA ON YMTRADEITM.STRATEGY = STRA.STRATEGY
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBUSER AS YMTRTBUSER ON YMTRADEHDR.TRADER = YMTRTBUSER.BNAME
		LEFT JOIN HS_NASTRIPES_SLT.OIJLOC AS OIJLOC ON YMTRADEITM.TITLE_LOC = OIJLOC.LOCID
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRPGM as STRPGM on STRA.YPROGRAM = STRPGM.YPROGRAM
		LEFT JOIN HS_NASTRIPES_SLT.YMTRTBSTRTR2 as STRTR2 on STRTR2.TIER_II = STRA.TIER_II

WHERE	YMTRADEHDR.END_DATE >= '20210801'
		AND YMTRADEHDR.TRADE_TYPE NOT IN ('TSRV','TINT') -- Exclude LASS and internal trades
		AND YMTRADEITM.ITEM_TYPE = 'L' -- No ship to or delivery options
		AND YMTRADEHDR.DEAL_STATUS <> 'DELE'
