SELECT 	YMTRTBUSER.BNAME
		, YMTRTBUSER.NAME1
		, CASE 
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'TRDN' THEN 'Trader' 
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'CNTA' THEN 'Contract admin'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'APRV' THEN 'Approver'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'SCDN' THEN 'Scheduler'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'DSAC' THEN 'Downstream Accounting'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'FCTR' THEN 'Facilitator'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'PRCN' THEN 'Pricing Analyst'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'REGL' THEN 'Regulatory'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'USAC' THEN 'Upstream Accouting'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'RISK' THEN 'Risk Analyst'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'BHWC' THEN 'Blend hub coordinator'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'TSA' THEN 'Trade Support Analyst'
			ELSE 'Other'
		END AS "USER_TYPE"
		, YMTRTBUSER.EMAIL_ID
		, YMTRTBUSERTYPE.VALID_FROM
		, YMTRTBUSERTYPE.VALID_TO
		, GRDB.COUNTRY_CODE
		, GRDB.CITY_NAME
		, 'NA' AS "SYSTEM"
FROM HS_NASTRIPES_SLT.YMTRTBUSER AS YMTRTBUSER
INNER JOIN HS_NASTRIPES_SLT.YMTRTBUSERTYPE AS YMTRTBUSERTYPE ON YMTRTBUSER.BNAME = YMTRTBUSERTYPE.BNAME
LEFT OUTER JOIN HS_GRDB.GRDB_VW_PERSON AS GRDB ON GRDB.CORPORATE_SYSTEM_USER_INTERNET_MAILBOX_NAME = YMTRTBUSER.EMAIL_ID
WHERE YMTRTBUSERTYPE.VALID_TO > '20230628'

UNION

SELECT 	YMTRTBUSER.BNAME
		, YMTRTBUSER.NAME1
		, CASE 
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'TRDN' THEN 'Trader' 
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'CNTA' THEN 'Contract admin'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'APRV' THEN 'Approver'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'SCDN' THEN 'Scheduler'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'DSAC' THEN 'Downstream Accounting'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'FCTR' THEN 'Facilitator'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'PRCN' THEN 'Pricing Analyst'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'REGL' THEN 'Regulatory'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'USAC' THEN 'Upstream Accouting'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'RISK' THEN 'Risk Analyst'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'BHWC' THEN 'Blend hub coordinator'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'TSA' THEN 'Trade Support Analyst'
			ELSE 'Other'
		END AS "USER_TYPE"
		, YMTRTBUSER.EMAIL_ID
		, YMTRTBUSERTYPE.VALID_FROM
		, YMTRTBUSERTYPE.VALID_TO
		, GRDB.COUNTRY_CODE
		, GRDB.CITY_NAME
		, 'EU' AS "SYSTEM"
FROM HS_EUSTRIPES_SLT.YMTRTBUSER AS YMTRTBUSER
LEFT OUTER JOIN HS_NASTRIPES_SLT.YMTRTBUSERTYPE AS YMTRTBUSERTYPE ON YMTRTBUSER.BNAME = YMTRTBUSERTYPE.BNAME
LEFT OUTER JOIN HS_GRDB.GRDB_VW_PERSON AS GRDB ON GRDB.CORPORATE_SYSTEM_USER_INTERNET_MAILBOX_NAME = YMTRTBUSER.EMAIL_ID
WHERE YMTRTBUSERTYPE.VALID_TO > '20230628'

UNION

SELECT 	YMTRTBUSER.BNAME
		, YMTRTBUSER.NAME1
		, CASE 
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'TRDN' THEN 'Trader' 
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'CNTA' THEN 'Contract admin'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'APRV' THEN 'Approver'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'SCDN' THEN 'Scheduler'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'DSAC' THEN 'Downstream Accounting'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'FCTR' THEN 'Facilitator'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'PRCN' THEN 'Pricing Analyst'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'REGL' THEN 'Regulatory'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'USAC' THEN 'Upstream Accouting'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'RISK' THEN 'Risk Analyst'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'BHWC' THEN 'Blend hub coordinator'
			WHEN YMTRTBUSERTYPE.USER_TYPE = 'TSA' THEN 'Trade Support Analyst'
			ELSE 'Other'
		END AS "USER_TYPE"
		, YMTRTBUSER.EMAIL_ID
		, YMTRTBUSERTYPE.VALID_FROM
		, YMTRTBUSERTYPE.VALID_TO
		, GRDB.COUNTRY_CODE
		, GRDB.CITY_NAME
		, 'AP' AS "SYSTEM"
FROM HS_APSTRIPES_SLT.YMTRTBUSER AS YMTRTBUSER
LEFT OUTER JOIN HS_NASTRIPES_SLT.YMTRTBUSERTYPE AS YMTRTBUSERTYPE ON YMTRTBUSER.BNAME = YMTRTBUSERTYPE.BNAME
LEFT OUTER JOIN HS_GRDB.GRDB_VW_PERSON AS GRDB ON GRDB.CORPORATE_SYSTEM_USER_INTERNET_MAILBOX_NAME = YMTRTBUSER.EMAIL_ID
WHERE YMTRTBUSERTYPE.VALID_TO > '20230628'

